export const categories = [
    { value: "clothing", label: "Clothing & Apparel" },
    { value: "electronics", label: "Electronics & Gadgets" },
    { value: "grocery", label: "Grocery & Supermarkets" },
    { value: "restaurant", label: "Restaurants & Cafés" },
    { value: "beauty", label: "Beauty & Personal Care" },
    { value: "furniture", label: "Furniture & Home Decor" },
    { value: "automotive", label: "Automotive & Accessories" },
    { value: "books", label: "Books & Stationery" },
    { value: "toys", label: "Toys & Games" },
    { value: "sports", label: "Sports & Fitness" },
    { value: "hardware", label: "Hardware & Tools" },
    { value: "pet", label: "Pet Supplies & Services" },
    { value: "medical", label: "Medical & Pharmacy" },
    { value: "jewelry", label: "Jewelry & Watches" },
    { value: "florist", label: "Florists & Gift Shops" },
    { value: "baby", label: "Baby & Kids Store" },
    { value: "art", label: "Art & Craft Supplies" },
    { value: "music", label: "Music Instruments & Stores" },
    { value: "shoes", label: "Shoes & Footwear" },
    { value: "bags", label: "Bags, Luggage & Travel" },
    { value: "office", label: "Office Supplies" },
    { value: "kitchen", label: "Kitchenware & Appliances" },
    { value: "garden", label: "Garden & Outdoor" },
    { value: "gaming", label: "Gaming & Consoles" },
    { value: "movies", label: "Movies & Entertainment" },
    { value: "alcohol", label: "Wine, Beer & Spirits" },
    { value: "health", label: "Health & Wellness" },
    { value: "cleaning", label: "Cleaning & Household" },
    { value: "stationery", label: "School & Stationery" },
    { value: "tech", label: "Tech Accessories" }
];
