export const shopCategories = [
    { value: "clothing", label: "Clothing & Apparel" },
    { value: "electronics", label: "Electronics & Gadgets" },
    { value: "grocery", label: "Grocery & Supermarkets" },
    { value: "restaurant", label: "Restaurants & Cafés" },
    { value: "beauty", label: "Beauty & Personal Care" },
    { value: "furniture", label: "Furniture & Home Decor" },
    { value: "automotive", label: "Automotive & Accessories" },
    { value: "books", label: "Books & Stationery" },
    { value: "toys", label: "Toys & Games" },
    { value: "sports", label: "Sports & Fitness" },
    { value: "hardware", label: "Hardware & Tools" },
    { value: "pet", label: "Pet Supplies & Services" },
    { value: "medical", label: "Medical & Pharmacy" },
    { value: "jewelry", label: "Jewelry & Watches" },
    { value: "florist", label: "Florists & Gift Shops" },
    { value: "baby", label: "Baby & Kids Store" },
    { value: "art", label: "Art & Craft Supplies" },
    { value: "music", label: "Music Instruments & Stores" },
    { value: "footwear", label: "Footwear & Shoes" },
    { value: "bags", label: "Bags & Luggage" },
    { value: "kitchen", label: "Kitchenware & Appliances" },
    { value: "stationery", label: "Office & Stationery Supplies" },
    { value: "gaming", label: "Gaming & Esports" },
    { value: "gardening", label: "Gardening & Outdoor Supplies" },
    { value: "lighting", label: "Lighting & Electricals" },
    { value: "alcohol", label: "Alcohol & Beverages" },
    { value: "bakery", label: "Bakery & Confectionery" },
    { value: "travel", label: "Travel & Luggage" },
    { value: "health", label: "Health & Wellness" },
    { value: "digital", label: "Digital Products & Software" },
    { value: "gift", label: "Gift Items & Souvenirs" },
    { value: "cleaning", label: "Cleaning Supplies" },
    { value: "construction", label: "Construction & Building Material" },
    { value: "industrial", label: "Industrial Equipment" },
    { value: "luxury", label: "Luxury Goods" },
    { value: "fastfood", label: "Fast Food & Snacks" },
    { value: "organic", label: "Organic Products" },
    { value: "mobile", label: "Mobile & Accessories" },
    { value: "homeappliances", label: "Home Appliances" },
    { value: "events", label: "Event & Party Supplies" },
    { value: "security", label: "Security & Safety Products" },
    { value: "diy", label: "DIY & Handicrafts" },
];
